Add "Protocols composition" spec
waku-org/specs pull request #19
Opened 2024-05-27 15:49 UTC by weboko

2025-03-16 23:46 UTC, weboko commented
Thumb up if you want me to walk you through the document on a short call. :)

2025-03-17 09:18 UTC, weboko commented on standards/application/messaging-api.md
> +##### `getPendingRequests`
I hope it can be resolved with `Message Storage API` which gives a way to fetch `MessageRecord` with associated `RequestID`. 

And I am not sure if it is the best strategy to do.

2025-03-17 09:24 UTC, weboko commented on standards/application/messaging-api.md
> +##### `getPendingRequests`
exactly! I am trying to enclose this logic in `Message Storage API` for `get` operations and relevant events in `Event Source API`

2025-03-17 09:47 UTC, weboko commented on standards/application/messaging-api.md
> +  mode: "edge" | "service";
General question to anyone from me:
- I don't believe we actually need this property AS `Messaging API` can be smart enough to determine and prioritize underlying protocols. 

I am in favor of removing it altogether giving a seamless way for mounting `Messaging API` on any node.

2025-03-17 14:52 UTC, vpavlin commented on standards/application/messaging-api.md
> +  serviceNodes?: string[];
Would the assumption be that same nodes are used for publishing and receiving (via lightpush and filter)? Since we have storeNodes separate, would it make sense to also have something like `publishNodes`, `listenNodes`?

2025-03-17 14:59 UTC, vpavlin commented on standards/application/messaging-api.md
> +[STORE](../standards/core/store.md) as well as host endpoint for [LIGHTPUSH](../standards/core/lightpush.md) and [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4ea
Requiring store does not feel right - Store nodes have different expectations than Lightpush and Filter nodes - those can come and go and still be useful (unless the fluctuation is in order of seconds or minutes), but Store (even with Store sync) should be more stable and available + enabling the protocol puts requirement on hosting the DB. 

I'd personally see store managed separately

2025-03-17 15:00 UTC, vpavlin commented on standards/application/messaging-api.md
> +[STORE](../standards/core/store.md) as well as host endpoint for [LIGHTPUSH](../standards/core/lightpush.md) and [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4ea
To add to it, I might be fine if my phone is a `service` node when on Wifi and plugged in the charger, but I would not want it to store GBs of random and "useless" data:)

2025-03-17 15:08 UTC, vpavlin commented on standards/application/messaging-api.md
> +  public getPendingRequests(): RequestID[];
Should there also be `isPending(requestId: RequestID)` method, or is iterating over `getPendingRequests()` result enough?

2025-03-17 15:17 UTC, vpavlin commented on standards/application/messaging-api.md
> +### Send
SHould it also mention what happens when the node is in `Unhealthy` state? Or is that implicit - sending will fail and it will be retried when the health changes to `minimally healthy` or `healthy`?

2025-03-17 15:24 UTC, vpavlin commented on standards/application/messaging-api.md
> +The subscription is based on the `pubsubTopic` and `contentTopic` provided by the `Decoder`,
As I mentioned above - would it make sense to move away from `pubsubTopic` in dev/user facing parts and only refer to `shard`?

2025-03-17 15:29 UTC, vpavlin commented on standards/application/messaging-api.md
> +If `confirmStored` is set to `true`, a recurring [STORE](../standards/core/store.md) query MUST be started.
I understood `confirmStored` as targetting sent messages (i.e. to confirm a message I published reached the network). 

What if I don't necessarily need `confirmStore` for sending (e..g I am just publishing an "I am online" heartbeat, so I don't really care if they are missed sometime), but I do care for regular store queries as I'd really like to make sure I get all the messages? 

Basically, are we conflating 2 separate features under `confirmStored`?

2025-03-17 15:32 UTC, vpavlin commented on standards/application/messaging-api.md
> +  "error": "Cannot create subscription. clusterId 0 is not supported."
There is no `clusterId` in `/subscribe` - this message would utterly confuse me as a developer:) Probably related to my question(s) about replacing `pubsubTopic` with `shard` (and then also adding `clusterid` to `/subscribe` for completeness)

2025-03-17 15:32 UTC, vpavlin commented on standards/application/messaging-api.md
> +HTTP/1.1 200 OK
Should there also be `404` or if the subscription does not exist, or would it return `200` since it is `ok`, kinda

2025-03-17 15:49 UTC, vpavlin commented on standards/application/messaging-api.md
> +GET /messages?contentTopic=/messaging/2/api/utf8&skip=0&take=10 HTTP/1.1
Should this be URL encoded?

2025-03-17 20:01 UTC, Ivansete-status reviewed
Thanks so much for it! :raised_hands: 
Some comments so far

2025-03-18 02:51 UTC, fryorcraken requested changes
I have reviewed half. I think it's enough comment for now.

Let me know if you prefer a full review.

Hopefully, lot of opportunity to thin it out.

2025-03-18 02:51 UTC, fryorcraken commented on standards/application/messaging-api.md
> +- If the initial configuration specifies mode: "service", then [RELAY](https://github.com/vacp2p/rfc-index/blob/0277fd0c4dbd907dfb2f0c28b6cde94a335e1fae/waku/standards/core/11/relay.md) MUST be used
I would not re-state that, it's infer from the mode of operation section

2025-03-18 02:51 UTC, fryorcraken commented on standards/application/messaging-api.md
> +- The decision to retry MUST be based on the underlying protocol’s response from a remote peer.
Two comments here:

1. This can be refer back to the p2p reliability spec
> The usual remedial action is to retransmit the message. 

I would not re-state this logic here. But instead, just clarifying that `send` API is expected to implement the strategies configured and stated in p2p reliability state.

2. Actual back-off timing can be left to implementater's choice

2025-03-18 02:51 UTC, fryorcraken commented on standards/application/messaging-api.md
> +from the most recently scheduled or retried request to the oldest.
I would not include that here. Implementation detail.

2025-03-18 02:51 UTC, fryorcraken commented on standards/application/messaging-api.md
> +- The decision to retry MUST be based on the underlying protocol’s response from a remote peer.
If there is one thing you should include or that cna be configurable is for how long do we retry - because this may be application dependent. but for now, I'll leave it to the implementation

2025-03-18 02:51 UTC, fryorcraken commented on standards/application/messaging-api.md
> +type Message = {
See my comment on writing it in C.

Do the same as https://github.com/vacp2p/rfc-index/blob/main/waku/standards/core/36/bindings-api.md#jsonmessage-type

2025-03-18 02:51 UTC, fryorcraken commented on standards/application/messaging-api.md
> +  public send(encoder: Encoder, message: Message): RequestID;
Not convinced encoder concept works here. Let's see how it looks on C API.

2025-03-18 02:51 UTC, fryorcraken commented on standards/application/messaging-api.md
> +  public cancelRequest(requestId: RequestID): void;
Do we need/use that? sounds too low level

2025-03-18 02:51 UTC, fryorcraken commented on standards/application/messaging-api.md
> +  public getPendingRequests(): RequestID[];
Ok very interesting here.

Due to the nature of Waku's domain (async network request), it seems much more appropriate to have an event based approach.

See https://github.com/vacp2p/rfc-index/blob/main/waku/standards/core/36/bindings-api.md#waku_set_event_callback

having `getRequestState` implies someone is going to loop on that - not a great design.

I'd remove in favor of event listening/callbacks

2025-03-18 02:51 UTC, fryorcraken commented on standards/application/messaging-api.md
> +Additionally, it MUST provide information regarding the `pubsubTopic` and `contentTopic` to which messages SHOULD be sent.
No mention of `pubsubtopic` in the API, we only deal with shards and clusters.

2025-03-18 02:51 UTC, fryorcraken commented on standards/application/messaging-api.md
> +
I would not define things twice. Only once in `C` and provide a recommendation on how this should translate to a REST API

2025-03-18 07:24 UTC, vpavlin commented on standards/application/messaging-api.md
> +  serviceNodes?: string[];
That is my understanding of this field - preferred service nodes, not "the only service nodes to use"

2025-03-18 07:32 UTC, vpavlin commented on standards/application/messaging-api.md
> +##### `Decoder`
This depends on how smart the Messaging API should be - e.g. in Waku Dispatcher my "onMsgReceived` function signature looks like this: https://github.com/vpavlin/waku-dispatcher/blob/main/src/dispatcher.ts#L135 - I kind of like the flexibility of using Encoder/Decoder gives us and potentially gives all the devs (I could implement my own Decoder which would do some smart validation or processing)

Another thing is you cannot just pass payload and contentTopic - the dev also needs the rest of the fields - like `meta`, `timestamp` or `rln proof`:)

2025-03-18 07:34 UTC, vpavlin commented on standards/application/messaging-api.md
> +### Message Storage
I think we need some Message Storage API:-) The naming might need to be tweaked, but as a dev, I want to be able to sift through the messages I have sent and received, to filter them, or verify things - and it would be bad if everyone had to implement this on their own - Messaging API is a great place for it:)  (speaking again based on what I needed in Waku Dispatcher - https://github.com/vpavlin/waku-dispatcher/blob/main/src/dispatcher.ts#L482)

2025-03-18 20:31 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +##### `Decoder`
> I kind of like the flexibility of using Encoder/Decoder gives us and potentially gives all the devs

ah okay I see. I have the impression that the Encoder/Decoder concept fits very well from typescript PoV but I wonder how it would fit from a C API PoV

----
> Another thing is you cannot just pass payload and contentTopic - the dev also needs the rest of the fields - like meta, timestamp or rln proof:)

Yes good point! I agree that `meta` and `timestamp` is needed but maybe `rln proof` not needed

2025-03-25 23:05 UTC, fryorcraken commented
Discussion around store abstraction: https://forum.vac.dev/t/no-store-in-messaging-api/455/4

2025-03-28 00:42 UTC, fryorcraken commented
I would also reserve a space for RLN. It's not in scope but I overlook to specify it https://www.notion.so/Waku-FURPS-1498f96fb65c803faedef2a591c22c00?d=1c48f96fb65c80369e8f001ca5c7e353&pvs=4#1578f96fb65c80778215ef012c6f6136

2025-03-28 06:35 UTC, chaitanyaprem reviewed
Reviewed till Send API, will continue filter review little later.

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +A list of `Multiaddr` addresses to remote peers that SHOULD be used for any applicable method of discovery that MAY include:
wondering if we should also allow the option to specify `ENR` in case of bootstrap/store/service nodes?

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +##### `confirmStored`
maybe call it as `sendConfirmations`?

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +An optional property that defaults to `false`.
maybe this should be set to true by default for edge nodes. 
maybe check the current default behaviour with status team and align with it as i am not aware of this.

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +If set to `true` and `confirmContentTopics` are provided, a recurring background [STORE](../standards/core/store.md) query (as described in the `Message Storage API` section) MUST be initiated.
Do we want to specify interval of these queries as well based on what is used in case of status (i.e 3 secs)?

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +If set to `true` without `confirmContentTopics`, the background [STORE](../standards/core/store.md) query (as described in the `Messaging Storage API` section) MUST only be initiated after the `Subsc
A user may not always subscribe to content-topics that they are publishing to. Hence this query is supposed to be based on `messageHashes` and not `contentTopics`. 
ContentTopics are to be used in-conjunction with filter only where user subscribes to them to receive messages.

 This field can be used along with `confirmReceived`  rather than `confirmStored`

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +
I would suggest this field to be used only for receive message confirmations. See reasoning in above comment.

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +  public cancelRequest(requestId: RequestID): void;
Agreed it is too low level, rather a more simpler approach would be for the user to indicate a timeout for the send API. The user can also pass a context(this might be too Golang specific but is a very good concept for an API in general)  which can be cancelled or timeout.

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +  public getPendingRequests(): RequestID[];
I agree with @fryorcraken here. It would be better to have an event based approach to indicate success/failure/timeout etc.

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +  public send(encoder: Encoder, message: Message): RequestID;
Why do we need to have an encoder? Shouldn't encoder be more like a utility from waku/sdk app devs can use to encode their payload and then supply WakuMessage to be sent? This gives flexibility for devs to decide whether to use Waku encoder or some other way to encode their messages.

This looks like better separate of concerns in case apps want to use their own way to encode different message types e.g: in status we have private messages which are encrypted/encoded differently and public messages which are done differently. Ultimately status backend handsover only WakuMessage to the send API which seems more cleaner to me.

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +This `GUID` MAY be used to cancel a scheduled request or to retrieve information about the associated message from the `Message Storage API`.
Why not use the term `messageHash` as it is used in Store API and in all other existing specs?

2025-03-28 06:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +A subscription is established via [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4eac4f6/waku/standards/core/12/filter.md) or [RELAY](https://github.com/vacp2p/rfc
Is this a good place to mention that subscription should be done to 2 filter service nodes?

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +The subscription is based on the `pubsubTopic` and `contentTopic` provided by the `Decoder`,
In case of relay contentTopic would be optional, whereas in case of Filter it is mandatory. Would be good to document his in the API so that users are aware based on the nodeType how the params are to be passed.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +If `confirmStored` is set to `true`, a recurring [STORE](../standards/core/store.md) query MUST be started.
I agree and think that we should have 2 configs as it is currently implemented in status. We have separate flag to indicate `sendConfirmations` vs `fetchMissingMessages`

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +No specific order is guaranteed for callback invocation;
Maybe better to add a note that users would need to have a way to deduplicate messages (returned by 2 filter subscriptions or store nodes etc). Or is that implemented underneath this API? If so, better to mention that as well for implementers.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +the call MUST be ignored.
wouldn't it be better to return an error indicating the same?

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +##### `Decoder`
> Another thing is you cannot just pass payload and contentTopic - the dev also needs the rest of the fields - like `meta`, `timestamp` or `rln proof`:)

Why not pass WakuMessage itself which has all these fields?

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +Additionally, it MUST filter messages based on the `contentTopic` to ensure that only relevant messages are processed.
I am confused about Decoder now. Since it is passed in Susbcribe API i assume that it expects messages belonging to the specific contentTopic and only does actual decoding of the message and not filtering of it. 

What if an app users wants to use different decoders for different contentTopics? Then would each Decoder receive messages of all topics that needs to be filtered? or am i missing something here.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +### Message Storage
How about we have this API only to do time-range based retrieval queries where a node has come back from offline state and wants history.

The hash based queries can be done behind the scenes as part of the Messaging API for reliability checks.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +Message storage is populated by:
Not sure why we want to explain Store functionality here or is this storage something else?

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +Depending on the presence of the `confirmStored` or `confirmReceived` options in the `Initial configuration`, the `Message Storage API` will trigger either the `Subscribe API` or the periodic [STORE]
Now i am totally confused here. Why is Message Storage API triggering a subscribe?

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +- It subscribes to [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4eac4f6/waku/standards/core/12/filter.md) or [RELAY](https://github.com/vacp2p/rfc-index/blob/027
why is a background operation subscribing to Filter/relay? isn't it the otherway around i.e if a user subscribes to filter and confirmReceived is set then those shards/content-topics are used for periodic message retrieval checks.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +Message acknowledgement is a background operation that performs the following functions:
Maybe refer this section above in confirm flags indicating the mechanism is described here.

I got confused at first wondering if this is in addition to periodic store query mechanism based on `confirm* `flags.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +These queries SHOULD occur once every 60 seconds for all `confirmContentTopics` provided as part of the initial configuration.
I think for sendConfirmations a shorter interval is used in case of status iirc it is `3seconds.`

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +The `Health Indicator API` SHOULD be used to monitor the operational health of a node operating under the `Messaging API`.
Here to 773 seems duplicate of 758-764.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +- `unhealthy`: Indicates that the node is in a degraded state and may not reliably process or transmit messages.
Doesn't this mean that node cannot process/transmit rather than being in degraded state. This indicates loss of connectivity for reception or sending or both.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +##### `minimally healthy`
which state would the node be in if it has connections to filter and lightpush but no connection to store nodes?
I am guessing. minimally healthy. maybe better to mention that explicitly as well.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +
Generic Comments:

1. Might be good to have a section listing all API's and referring to subsections for each of them. otherwise for a dev/user it would be hard to navigate the spec to read so much detail. 
2. Also it might be a good idea to provide an API for the user to get localNodeInfo i.e (MultiAddr node is listening on, ENR of the node if applicable). This would be useful in relay node+service node scenarios. So maybe this API is applicable only if node is initialized with relay/serviceNode.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +Registers an event listener for a specified `eventName` using the provided `EventHandler`.
Shouldn't eventListeners be automatically registered for many cases? 
i.e all message related events should be notified to the user such as sent/stored etc. 
wondering why a user should explicitly subscribe to such events?

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +The event’s payload (accessible via `event.detail`) is the new `HealthStatus` value (`Unhealthy`, `MinimallyHealthy`, or `Healthy`).
I am wondering if we should indicate store not reachable/not working as a separate state. Because in this case the node is connected to appropriate serviceNodes/relay-mesh but just that store confirmations/retrieval is not working. This seems like it is falling in between minimallyHealthy and Healthy. 

I am also not sure if we need a separate status for this but better to think about it.

2025-03-28 07:51 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +The `MessageRecord` is defined in the `Message Storage API` section.
Would be good to add a note that the callback is expected to not do any long processing so that underlying threads don't get blocked and drops messages. 

We have noticed this issue in status once where message's were getting dropped as the app thread was blocked due to some sync logic which was causing reliability issues.

2025-04-01 21:59 UTC, weboko commented on standards/application/messaging-api.md
> +  mode: "edge" | "service";
Then I keep `edge` and introduce `relay`. 
As for the `service`, correct me if I am wrong, but I think it is out of the scope of `Messaging API`.

2025-04-01 22:05 UTC, weboko commented on standards/application/messaging-api.md
> +  mode: "edge" | "service";
https://github.com/waku-org/specs/pull/19/commits/b6e6e6291fde668ea9d9829c63a762ea02145b62

2025-04-01 22:34 UTC, weboko commented on standards/application/messaging-api.md
> +This document specifies an Application Programming Interface (API) that is RECOMMENDED for consumers of the [WAKU2](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4eac4f6/w
updated https://github.com/waku-org/specs/pull/19/commits/04cd4bfbcf53669c4007af8fe529b6717de5f0cd

2025-04-01 22:34 UTC, weboko commented on standards/application/messaging-api.md
> +- [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4eac4f6/waku/standards/core/12/filter.md)
removed this block https://github.com/waku-org/specs/pull/19/commits/04cd4bfbcf53669c4007af8fe529b6717de5f0cd

2025-04-01 22:43 UTC, weboko commented on standards/application/messaging-api.md
> +Although recommendations such as [P2P-RELIABILITY](./p2p-reliability.md) have been introduced to enhance protocol robustness,
improved text here https://github.com/waku-org/specs/pull/19/commits/f1d100fd6c1fa486cd26216dcf10bd4726ae7be2

2025-04-01 22:45 UTC, weboko commented on standards/application/messaging-api.md
> +
Added table of content https://github.com/waku-org/specs/pull/19/commits/f1d100fd6c1fa486cd26216dcf10bd4726ae7be2

As for (2) - I think it is out of scope of `Messaging API` as this is something that, I think, must be provided by any Waku client. 

We can thought use an opportunity here to specify it. Let me know if you are in favor of it and I will push that change, @chaitanyaprem .

2025-04-01 22:53 UTC, weboko commented on standards/application/messaging-api.md
> +This API is designed for generic use and ease of implementation across `nwaku`, `js-waku`,
https://github.com/waku-org/specs/pull/19/commits/d8796b6a780780411187792e1cf585d1ba3168f6

2025-04-01 22:53 UTC, weboko commented on standards/application/messaging-api.md
> +This API is designed for generic use and ease of implementation across `nwaku`, `js-waku`,
made it simply `across all implementations and REST`

2025-04-01 23:00 UTC, weboko commented on standards/application/messaging-api.md
> +  storeNodes?: string[];
This is interesting design decision I'd like to discuss.

In this proposal I specify following:
`If not provided, nodes discovered through the network SHOULD be used.`

So that, a client implementing `Messaging API` would attempt to recover at least somehow. 
Downside here is that provided service might not be ideal.

Allowing a client to recover can be a way to go as we might have in future stable network, better nodes etc. 
Contrary not providing service is an option as this will make project developers cautious AND willing to do their setup for better overall end experience.

I specified `recovery` approach as this is something, I believe, of a current behavior.

2025-04-01 23:03 UTC, weboko commented on standards/application/messaging-api.md
> +  serviceNodes?: string[];
renaming to `preferredServiceNodes` as this is original intention and specified in description already

2025-04-01 23:22 UTC, weboko commented on standards/application/messaging-api.md
> +  confirmStored?: boolean;
there is an art to naming, and it's hard...

renaming this and `confirmReceived` as I think both must follow the same naming 

the other one is `filterConfirmation` 

https://github.com/waku-org/specs/pull/19/commits/e60bd6f6248c0f7d2c5b967ef7910193b3b394c2

2025-04-01 23:22 UTC, weboko commented on standards/application/messaging-api.md
> +  serviceNodes?: string[];
https://github.com/waku-org/specs/pull/19/commits/e60bd6f6248c0f7d2c5b967ef7910193b3b394c2

2025-04-01 23:24 UTC, weboko commented on standards/application/messaging-api.md
> +##### `confirmStored`
very difficult, named it `sotreConfirmation` to give some hint about protocol used too
https://github.com/waku-org/specs/pull/19/commits/e60bd6f6248c0f7d2c5b967ef7910193b3b394c2

2025-04-01 23:24 UTC, weboko commented on standards/application/messaging-api.md
> +##### `confirmReceived`
https://github.com/waku-org/specs/pull/19/commits/e60bd6f6248c0f7d2c5b967ef7910193b3b394c2

2025-04-02 01:14 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +##### `confirmStored`
wondering if giving protocol name is a good idea, anyways since this is supposed to be abstracting protocols would it be better to call it `sendConfirmations` ? as this flag is used only to confirm via store messages which are sent out, better to indicate that in the name.

2025-04-02 05:13 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +
> As for (2) - I think it is out of scope of `Messaging API` as this is something that, I think, must be provided by any Waku client.

ok, since we are defining the API i thought we can provide this as well as it might be useful for users to know their nodeinfo. We can add it as it is a small API.

2025-04-02 22:02 UTC, weboko commented on standards/application/messaging-api.md
> +and [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4eac4f6/waku/standards/core/12/filter.md) for receiving messages.
@Ivansete-status I am not sure I understand this comment, can you elaborate, please?

2025-04-02 22:12 UTC, weboko commented on standards/application/messaging-api.md
> +and [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4eac4f6/waku/standards/core/12/filter.md) for receiving messages.
https://github.com/waku-org/specs/pull/19/commits/37d7e7ef52cdd90a4820306114f2d0678e2469ed

2025-04-02 22:14 UTC, weboko commented on standards/application/messaging-api.md
> +
sure, it's only couple of lines
which part of API do you think it fits best, @chaitanyaprem ?

2025-04-02 22:16 UTC, weboko commented on standards/application/messaging-api.md
> +An array of shard under a specified cluster that node MUST operate at as per [RELAY-SHARDING](https://github.com/waku-org/specs/blob/186ce335667bdfdb6b2ce69ad7b2a3a3791b1ba6/standards/core/relay-shar
By this description I implied that this is a list of shards that node is interested in, i.e `MUST operate at`
is present description misleading, @chaitanyaprem ?

2025-04-02 22:19 UTC, weboko commented on standards/application/messaging-api.md
> +- infrequent [STORE](../standards/core/store.md) queries;
yes, my intent to have following approach for store:
- if `storeNodes` provided they are used else:
- if `preferredServiceNodes` they are used else:
- try to use discovered nodes at this point:
- or fail.

This is a design decision to make here, I describe it here. 
Comment what you think is better - https://github.com/waku-org/specs/pull/19/files#r2023781573

2025-04-02 22:35 UTC, weboko commented on standards/application/messaging-api.md
> +If not provided, nodes discovered through the network SHOULD be used.
good point, added this change
https://github.com/waku-org/specs/pull/19/commits/f6516dad45eafcbd1e5b46d690e3396019540fbb

2025-04-02 22:43 UTC, weboko commented on standards/application/messaging-api.md
> +This `GUID` MAY be used to cancel a scheduled request or to retrieve information about the associated message from the `Message Storage API`.
@chaitanyaprem 

since [message hash](https://github.com/vacp2p/rfc-index/blob/main/waku/standards/core/14/message.md#deterministic-message-hashing) takes into account `timestamp` - due to retries it can change over time

hence we need a better way to identify requests TO `Messaging API` FOR sending a message
then we have a way to match `RequestID` with end `message hash`

This was my reasoning here, let me know what you think!

2025-04-02 22:57 UTC, weboko commented on standards/application/messaging-api.md
> +An optional property that defaults to `false`.
asked question, for now assuming it to be default `on` so defining it to be `true`
https://github.com/waku-org/specs/pull/19/commits/cd55755ffc4e7209dc7640c709619a806af1a39e

2025-04-02 23:26 UTC, weboko commented on standards/application/messaging-api.md
> +Registers an event listener for a specified `eventName` using the provided `EventHandler`.
I am not sure it is possible, to me it seems consumer of the API must somehow pass a reference to `EventHandler` they have, and this is something that can't be done automatically 
unless we expose new parameter in `Initial Configuration` for setting a callback

2025-04-02 23:33 UTC, weboko commented on standards/application/messaging-api.md
> +The event’s payload (accessible via `event.detail`) is the new `HealthStatus` value (`Unhealthy`, `MinimallyHealthy`, or `Healthy`).
That's difficult question.

On one side we want to provide granular way for consumers of the API to react to underlying changes,
on the other side if we expose too much consumers might get lost.

Also with Store it is more complicated as we want to hide it as much as possible.
And on top of that, even if we provide all the health status changes - what reaction do we anticipate?

In present format `HealthManager` covers UI changes so that:
- `unhealthy` -> notify user they are offline;
- `minimally healthy` -> raise a warning that some features may not work BUT rely on underlying guarantees described in the spec, e.g when back online to re-send messages, re-query Store, re-subscribe to Filter;
- `healthy` -> proceed with regular execution;

Maybe instead of exposing `StoreMissing` we should describe another mechanism that will ensure that:
- if node was online but skipped Store queries that were scheduled - it MUST recover messages for that time window;

wdyt @chaitanyaprem and maybe @vpavlin ?

2025-04-02 23:50 UTC, weboko commented on standards/application/messaging-api.md
> +##### `minimally healthy`
good question, I am not sure
`Store` is important but it doesn't actually cause functionality looses for a node, unless it is expected to get confirmations

so I didn't add it in the description here

2025-04-03 11:11 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +An array of shard under a specified cluster that node MUST operate at as per [RELAY-SHARDING](https://github.com/waku-org/specs/blob/186ce335667bdfdb6b2ce69ad7b2a3a3791b1ba6/standards/core/relay-shar
for autosharding logic to work properly there must be a config somewhere to be specified how many shards are there in the cluster. 
wanted to know which config is this one. if it is only the shards the node is interested in, then we may need to specify another config to indicate total shards in the network. 
e.g cluster-id 1 has 8 shards, but node is only interested in shards 0,1 then this config will list [0,1]. 
But somewhere shardCount 8 also has to be specified so that autosharding logic can use that to determine shard based on contentTopic.

2025-04-03 11:12 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +
I am guessing where we have health indicator.

2025-04-03 11:14 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +This `GUID` MAY be used to cancel a scheduled request or to retrieve information about the associated message from the `Message Storage API`.
ok, i see what you mean. I am wondering this may pose challenge in quering message from store as user won't have messageHash to work with or use SDS (as i think it relies on messageHashes).

But then again if the idea is to abstract away both of these from user, then it is fine i guess. But this is more of a transactionID between user and local waku messaging API and nothing beyond that right.

2025-04-03 11:20 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +Registers an event listener for a specified `eventName` using the provided `EventHandler`.
ok..got it. i was thinking of receiving because anyways callback would be provided for filter messages. 
But for sending side user may need to register explicitly or pass a callback while invoking send.

2025-04-04 18:03 UTC, weboko commented on standards/application/messaging-api.md
> +An array of shard under a specified cluster that node MUST operate at as per [RELAY-SHARDING](https://github.com/waku-org/specs/blob/186ce335667bdfdb6b2ce69ad7b2a3a3791b1ba6/standards/core/relay-shar
actually you are right, I missed it
for some reason I thought all auto shard clusters expected to have 8 shards 
adding an option for it with default value being 8 shards

let me know if you agree with that - https://github.com/waku-org/specs/pull/19/commits/cb446bd873a463abc6edfb212a218798809da2d9

on a side note - it seems `numbers of shards` is only needed for deriving shard from content topic
in that sense, shouldn't it be included into content topic format itself?

2025-04-04 19:18 UTC, weboko commented on standards/application/messaging-api.md
> +If set to `true` and `confirmContentTopics` are provided, a recurring background [STORE](../standards/core/store.md) query (as described in the `Message Storage API` section) MUST be initiated.
@chaitanyaprem specified it here 
https://github.com/waku-org/specs/pull/19/commits/face579a70ff8b1cbf0c1aec18908960495812b5

2025-04-04 19:28 UTC, weboko commented on standards/application/messaging-api.md
> +The event’s payload (accessible via `event.detail`) is the new `HealthStatus` value (`Unhealthy`, `MinimallyHealthy`, or `Healthy`).
specified message recovery after offline here https://github.com/waku-org/specs/pull/19/commits/face579a70ff8b1cbf0c1aec18908960495812b5

2025-04-04 20:09 UTC, weboko commented on standards/application/messaging-api.md
> +If set to `true` without `confirmContentTopics`, the background [STORE](../standards/core/store.md) query (as described in the `Messaging Storage API` section) MUST only be initiated after the `Subsc
this is a good point, I misses this case completely
here is definition for this behavior https://github.com/waku-org/specs/pull/19/commits/ed996f3aa5ea310df03bdf18336adb2ed9f332cc

2025-04-04 20:22 UTC, weboko commented on standards/application/messaging-api.md
> +If set to `true`, the node MUST initiate a network listener for messages circulated under `confirmContentTopics` via either [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5ad
Initially, I aimed to keep this spec self-contained,
but after revisiting p2p-reliability, I realize it makes more sense to link them properly.

Leaving this comment open until I find a good way to handle the integration.

2025-04-04 20:36 UTC, weboko commented on standards/application/messaging-api.md
> +### Send
it's specified in `Retry` section below, if it is not clear, please, re-open this comment

2025-04-06 19:53 UTC, weboko commented on standards/application/messaging-api.md
> +from the most recently scheduled or retried request to the oldest.
This should be handled by the node implementing `Messaging API` after `Send API` was triggered. 
Does that answer your question, @Ivansete-status ?

2025-04-07 00:35 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +An array of shard under a specified cluster that node MUST operate at as per [RELAY-SHARDING](https://github.com/waku-org/specs/blob/186ce335667bdfdb6b2ce69ad7b2a3a3791b1ba6/standards/core/relay-shar
> on a side note - it seems `numbers of shards` is only needed for deriving shard from content topic
> in that sense, shouldn't it be included into content topic format itself?

well, the idea was to make users agnostic to shards altogether and only use content-topic. but as each cluster can define its own number of shards, it is requiring to be configured locally. Note that the ideal way to get this info would be through some network configuration made maybe inside RLN contract rather than local configuration. As we don't have network configuration specified anywhere as of now, it is required to be configured locally. 

The idea of encoding shard-count in content-topic would  create a dependency of content-topic on shard count. In a cluster ideally the number of shards can change over time based on the network's requirements e.g today cluster 1 has 8 shards based on some napkin math of network requirements and bandwidth usage, but this may get increased in future. If we make content-topic format dependent on shard-count this would create problem to all existing content-topics when shard count changes in the network and would require migration etc.

2025-04-07 00:37 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +An array of shard under a specified cluster that node MUST operate at as per [RELAY-SHARDING](https://github.com/waku-org/specs/blob/186ce335667bdfdb6b2ce69ad7b2a3a3791b1ba6/standards/core/relay-shar
> let me know if you agree with that - [cb446bd](https://github.com/waku-org/specs/commit/cb446bd873a463abc6edfb212a218798809da2d9)

maybe the order and naming of config could be something like this as clusterId and shardsInCluster are network level config which are not specific to node being initialized whereas `shardsOfInterest` is something specific to the local node.

```
clusterId:
shardsInCluster:
shardsOfInterest:
```

2025-04-07 00:39 UTC, chaitanyaprem commented on standards/application/messaging-api.md
> +If set to `true` and `confirmContentTopics` are provided, a recurring background [STORE](../standards/core/store.md) query (as described in the `Message Storage API` section) MUST be initiated.
> meanwhile isn't 3 seconds is a short window?
> I thought of 10s or 30s and only if messages were `LightPushed` since we'll have active `Filter` subscription

iirc i think initially it was higher(maybe 5 or 10secs initially) but since status UI uses store confirmation to show message-status to the user 3sec was optimal to not have bad ux.

2025-04-07 08:35 UTC, weboko commented on standards/application/messaging-api.md
> +The `Health Indicator API` SHOULD be used to monitor the operational health of a node operating under the `Messaging API`.
indeed, removed

2025-04-07 08:44 UTC, weboko commented on standards/application/messaging-api.md
> +- `unhealthy`: Indicates that the node is in a degraded state and may not reliably process or transmit messages.
agree, improved wording here 
https://github.com/waku-org/specs/pull/19/commits/f401e5842d64b18f8e5fe34707a8f9d30a267fb4

2025-04-08 08:16 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +and [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4eac4f6/waku/standards/core/12/filter.md) for receiving messages.
> @Ivansete-status I am not sure I understand this comment, can you elaborate, please?

Sure! The `edge` nodes must act as both `lightpush-client` and `filter-client`. In both cases, the `edge` node is not directly mounting `LIGHTPUSH` nor `FILTER` protocols. Instead, the edge node just dial peers that mount those protocols. Therefore, I think is more precise to mention that.

Another option would be something like:

`MUST use [LIGHTPUSH](../standards/core/lightpush.md) as a client and connect to peers that mount LIGHTPUSH`

and

`[FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4eac4f6/waku/standards/core/12/filter.md) as a client and connect to peers that mount FILTER`

2025-04-10 01:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +A subscription is established via [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4eac4f6/waku/standards/core/12/filter.md) or [RELAY](https://github.com/vacp2p/rfc
I think we should refer to p2p reliability spec instead, and not add such implementation detail here.

2025-04-10 01:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +The subscription is based on the `pubsubTopic` and `contentTopic` provided by the `Decoder`,
> In case of relay contentTopic would be optional, whereas in case of Filter it is mandatory. 

Well, ideally one uses autosharding, making it the same interface for both relay and filter :)

2025-04-10 01:48 UTC, fryorcraken commented on standards/application/messaging-api.md
> +Additionally, it MUST filter messages based on the `contentTopic` to ensure that only relevant messages are processed.
`Decoder` was mainly created to cope with the `version=1` concept, which itself, should also go away :)

2025-04-10 02:00 UTC, fryorcraken commented on standards/application/messaging-api.md
> +  storeNodes?: string[];
I agree with what you are saying, I am just saying that in terms of terminology, I believe `staticStoreNode` better convey the functionality you have described. Because you specific static nodes to use, instead of finding nodes in the network (when not specified)

2025-04-17 01:23 UTC, weboko commented on standards/application/messaging-api.md
> +- Abstracts new primitives to be accessed in a RESTful manner via [Waku REST API](https://waku-org.github.io/waku-rest-api/).
good point https://github.com/waku-org/specs/pull/19/commits/1e4227ac80a507f09f3f3d2c757277c2206a4e6c

2025-04-17 01:23 UTC, weboko commented on standards/application/messaging-api.md
> +If set to `true`, the node MUST initiate a network listener for messages circulated under `confirmContentTopics` via either [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5ad
aligned with p2p-reliability spec in https://github.com/waku-org/specs/pull/19/commits/1e4227ac80a507f09f3f3d2c757277c2206a4e6c

2025-04-17 01:24 UTC, weboko commented on standards/application/messaging-api.md
> +- The decision to retry MUST be based on the underlying protocol’s response from a remote peer.
also agree, addressed here https://github.com/waku-org/specs/pull/19/commits/1e4227ac80a507f09f3f3d2c757277c2206a4e6c

2025-04-17 01:24 UTC, weboko commented on standards/application/messaging-api.md
> +from the most recently scheduled or retried request to the oldest.
done https://github.com/waku-org/specs/pull/19/commits/1e4227ac80a507f09f3f3d2c757277c2206a4e6c

2025-04-17 01:27 UTC, weboko commented on standards/application/messaging-api.md
> +Additionally, it MUST filter messages based on the `contentTopic` to ensure that only relevant messages are processed.
I wanted to bring concept of `Decoder` as a convenient abstraction but I now think it's more of `implementation details` and nothing to do with the spec

will remove it

2025-04-17 01:31 UTC, weboko commented on standards/application/messaging-api.md
> +A subscription is established via [FILTER](https://github.com/vacp2p/rfc-index/blob/7b443c1aab627894e3f22f5adfbb93f4c4eac4f6/waku/standards/core/12/filter.md) or [RELAY](https://github.com/vacp2p/rfc
simplified this section a bit https://github.com/waku-org/specs/pull/19/commits/1e4227ac80a507f09f3f3d2c757277c2206a4e6c and https://github.com/waku-org/specs/pull/19/commits/4523673bdc9365580eec792059898d504cfccb90

2025-04-17 01:33 UTC, weboko commented on standards/application/messaging-api.md
> +  storeNodes?: string[];
right :) https://github.com/waku-org/specs/pull/19/commits/b7e0e0b48fb274290e11afef25e6bfcf3f4e1a29

2025-04-17 01:36 UTC, weboko commented on standards/application/messaging-api.md
> +  public cancelRequest(requestId: RequestID): void;
I thought of having it as a backup for consumers to have granular control 
but after all discussions with you I think maybe some `start` and `stop` methods will be enought

2025-04-17 02:41 UTC, fryorcraken commented on standards/application/messaging-api.md
> +  mode: "edge" | "service";
Are we suggesting that for now, if one wants to run a store node or full blow service node, they would use a binary such a `wakunode2` and not the messaging API?

Sounds fair (for now).

2025-04-17 02:44 UTC, fryorcraken commented on standards/application/messaging-api.md
> +relevant code blocks will be provided in `JSON` format, `HTTP` format or by using `TypeScript` syntax.
Have you considered moving to a C syntax @weboko ?
I think derivation from C to REST API, TypeScript, etc can then be left to the implementation (ish)

2025-04-17 05:46 UTC, fryorcraken reviewed
good job. You did not address the question of language. I suggest to try C with a programmatic way of deriving the REST API indicators.

I have commented and there are a number of things that can be left to implementation detail. The spec is being too detailed right now.

I also expressed some opinion around the (local) message storage. I think it should be the opposite where we should define an API here of what a storage solution MUST implement (ie, provided by application developer), for the waku node to use.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +A list of `Multiaddr` addresses to remote peers that MUST be used for any applicable method of discovery that MAY include:
multiaddrs, enrs or enrtrees

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +
I don't understand the difference. is `receiveConfirmation` something more general? ie, can either use store or filter?
the name is misleading because "receive" implies that the target recipient received the message which an e2e reliability matter, out of scope for now.

I think I would say that we can have a `networkConfirmation` setting.
And remove `storeConfirmation`. and leave it to the implementation on whether a filter subscription or a store query is used to this confirmation.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +as defined in the [TOPICS](https://github.com/vacp2p/rfc-index/blob/8ee2a6d6b232838d83374c35e2413f84436ecf64/waku/informational/23/topics.md#content-topic-format) specification.
I'd remove that. I assume this because you want to be able to setup some filter subscription for content topics the user will send to?
We are making the API more complex here. It seems that filter confirmations are unpractical?

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +  timestamp?: number;
Remove this. The implementation should be the one setting the timestamp.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +  public cancelRequest(requestId: RequestID): void;
let's do simple first. https://www.notion.so/Waku-Mission-and-Methodology-1a58f96fb65c80b9b789c1bbb9e99915?pvs=4#1d78f96fb65c802c928af2576c55bc20

So yes, start/stop sounds fair

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +This `GUID` MAY be used to cancel a scheduled request or to retrieve information about the associated message from the `Message Storage API`.
I think it's fine for the request id to be purely implementation specific, and mainly used to track events.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +
I'd avoid those if possible. I assume `pending request` is mainly useful for REST API so fine to keep, but maybe we can specify that it's optional to implement in a language API.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +
@weboko thoughts on this?

IMO

define a C API:

```
char* waku_send(char* message, int shard, int timeoutMs, WakuCallBack onOkCb, WakuCallBack onErrorCb){}
```

and define a way to deduce the REST endpoint:
1. name function because route, `_` becomes `/`
2. data arguments are properties of the JSON payload
3. bytes payload are encoded in base64
4. callbacks are properties on the response JSON/websocket

Which would be:

``
POST /waku/send

{
	message: WakuMessageJSON,
	shard: number,
}
```

etc

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +  public subscribe(decoder: Decoder, fn: SubscriptionListener): SubscriptionID;
I would remove decoder.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +No specific order is guaranteed for callback invocation;
yes I agree here, we may need to define a deduplication logic on payload within a timeframe.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +the call MUST be ignored.
I think ignore is fine, because you may to unsubscribe for a clean shutdown but if the remote node already unsubscribe you because you were disconnected or something, you dont' want to be collecting errors.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +##### `Decoder`
I would move away from the Decoder in the context of the spec.

But js-waku is welcome to have an abstraction specific to JS/TS over the messaging API is decoder/encoder is a better dev ex.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +### Message Storage
I think we are talking about local storage. Hence, i would rename to `Local Message Storage API`.

I would NOT include this at this point in time, and would instead aim for the scope to be narrower and spec leaner.

**However**, I believe that the opposite is missing. A Waku implementation needs access to a local DB or cache to function properly, and remember message ids. etc.
This should be defined here. See how go-waku interfaces with status-go DB to mark messages as sent etc.

So when you start a node, there is a couple of components you should pass to your node, and we need to define the APIs those component must implement.
Another one is a `time source`, and `DNS source` (or maybe just DNS Servers ips or DoH addresses).

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +- Set the `stored` or `received` field on `MessageRecord` once the message is acknowledged according to store‑based reliability.
I would not use the term `acknowledgements` as it implies e2e reliability.

I would not list all of those and leave it to implementation detail. just refer to p2p reliability.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +Defaults to `false`.
The concept of `default` does not make sense here.
it's either `true` because there's still attempt to send
or `false` because it stops sending due to giving up or being somewhat successful

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +Indicates whether a message, originating from the underlying node,
```suggestion
Indicates whether an outbound message,
```

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +the property MUST transition back to `false`.
```suggestion
the property MUST transition to `false`.
```

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +This property is not applicable to messages that are received by the node.
```suggestion
This property is not applicable to inbound messages.
```

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +Defaults to `false`.
```suggestion
```

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +This field is applicable only to messages sent by the underlying node.
```suggestion
This field is applicable only to outbound messages.
```

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +Indicates whether a message, sent by the underlying node via the `Send API`,
```suggestion
Indicates whether an outbound message, sent via the `Send API`,
```

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +This update occurs only after the `sending` property has transitioned back to `false`.
From what heuristics?

I think some clarification is needed.

I'd say:

Indicates whether a message was sent over-the-wire with a best effort heuristic depending on the outbound protocols used. In the case of Light Push, an OK response from the remote service node will set this property to `true`.
For relay, a seemingly healthy pool of peers will sent this to `true` as soon as the message has been written on the wire.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +If an error occurs during reception, the `error` field MUST be populated with implementation-specific details.
as discussed earlier, merged those to a  `confirmed` status.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +
Too many APIs, especially with `getPendingRequests` already there.

I would say pick ONE way to check on message status at first, and we can then extend as we learn from dogfooding.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +- `healthy`: Indicates that the node is operating optimally, with full support for message processing and transmission.
delete that and just referred to the verbose definition in eponymous sections below

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +##### `minimally healthy`
I would leave it to implementation details for now, until we have deduced strong heuristics across all implementations.

I would just say that while a node may be able to send or receive messages, the redundancy dictated by the relay and p2p reliability protocols are not inplace.

2025-04-17 05:46 UTC, fryorcraken commented on standards/application/messaging-api.md
> +- The [RELAY](https://github.com/vacp2p/rfc-index/blob/0277fd0c4dbd907dfb2f0c28b6cde94a335e1fae/waku/standards/core/11/relay.md) mesh includes connections to at least six other peers.
I think too detailed here, and I would instead say that the redundancy stipulated by the p2p reliability and relay protocls are fulfilled.

2025-06-18 20:33 UTC, Ivansete-status reviewed
Great stuff in this PR @weboko :raised_hands: !

Nevertheless, the PR's content seems a bit beyond the PR's title.

I would suggest simplifying/splitting this as much as possible and narrow down the `messaging-api`'s scope. There are points that may better fit into `waku-api`, or `history-api`, f.e.

Thanks again for it and let's keep chatting !

2025-06-18 20:33 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +relevant code blocks will be provided in `JSON` format, `HTTP` format or by using `TypeScript` syntax.
C seems to be the standard for FFI definitions
On the other hand, I also like the `yaml` approach that @fryorcraken uses in https://github.com/waku-org/specs/pull/65

2025-06-18 20:33 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +  mode: "edge" | "relay";
@fryorcraken - IMO, the best names are `client` and `server`; or `client` and `web3-server`, if you want to emphasize its decentralized nature.
That way, the terms are more self-explanatory.

2025-06-18 20:33 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +An array of shard under a specified cluster that node MUST operate at as per [RELAY-SHARDING](https://github.com/waku-org/specs/blob/186ce335667bdfdb6b2ce69ad7b2a3a3791b1ba6/standards/core/relay-shar
IMO, we should decide the number of shards each cluster will have and deploy the SDK highly opinionated, in that regard.
The users should only pick up the `cluster-id` and the `content-topic`. Then, use autosharding underneath.

Therefore, these should not be allowed to be set, IMO:
```nim
shardsInCluster:
shardsOfInterest:
```

Giving the freedom to the SDK integrators to pick up the `shardsInCluster` is very dangerous because, on their app, they may start with `shardsInCluster=8`, f.e., but, what if the SDK integrator decides to change it to `shardsInCluster=16`? In that case, their network will get completely divided by the nodes running version with value `shardsInCluster=8` and nodes with `shardsInCluster=16`.

2025-06-18 20:33 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +##### `preferredServiceNodes`
Do you mean `bootstrapNodes`? I don't fully get why this is needed

2025-06-18 20:33 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +the implementation SHOULD use nodes discovered through the network.
The nodes should always be discovered, or inferred from the bootstrapNodes

2025-06-18 20:33 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +##### `storeConfirmation`
IMHO, that shouldn't be exposed

2025-06-18 20:33 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +##### `receiveConfirmation`
IMHO, this seems to be implicitly available by the SDK and therefore, no need to be exposed.

2025-06-18 20:33 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +### Message Storage
@vpavlin
> I think we need some Message Storage API:-)

Yes, I completely agree that a `history-API` is needed but I consider it belongs to the `waku-api` , instead of the `messaging-api`. That `history-API` may also implement internally the local cache storage mentioned on other comments.

2025-06-18 20:33 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +For the `REST API`, long polling over the `Message Store API` SHOULD be used.
Shall we leave all the `REST` definitions for 2026H1?

2025-06-18 20:33 UTC, Ivansete-status commented on standards/application/messaging-api.md
> +##### `health:change`
IMO, this should belong to `waku-api`

2025-06-20 03:41 UTC, fryorcraken commented
I suggest a more iterative and concise approach with https://github.com/waku-org/specs/pull/65, instead of the approach proposed in this current PR.

We also need to remember that spec and code should go together, hence why a more iterative approach where we have a we define and implement the API bit by bit.

The work done in this PR can serve as guidance/ground work for the final spec.

2026-04-23 09:58 UTC, jm-clius commented
@weboko @igor-sirotin I'm doing some housekeeping and this PR now seems stale. Can we close?

2026-05-02 22:02 UTC, closed without merging

2026-05-02 22:02 UTC, igor-sirotin commented
Yup, I'm gonna close it. 
I've used AI to analyze if any important details were missed in the current spec and didn't see anything critical.
But as I see this PR for sure served it's role to ignite the process 🫡

2026-05-03 06:58 UTC, weboko commented
it's 2y old PR...