feat: waku sync 2.0
waku-org/specs pull request #47
Opened 2024-12-05 16:35 UTC by SionoiS

WIP spec for Waku sync 2.0

2024-12-10 12:53 UTC, SionoiS commented
I still don't know what to write for varints.

I don't want to write a varint lib and I also think the Nim std impl. might change.

What do? @jm-clius

2024-12-11 14:20 UTC, jm-clius requested changes
Thanks for this!

I left some comments below, many of them nitpicks.
I think the main comment is around providing some context and a functional overview before jumping into the detail (at least of the `reconciliation` protocol). It can state the protocol flow and wire protocols in very simple terms:
1. what agents are involved (two nodes that store Waku messages)
2. what are the preconditions and goal (they want to initiate a bidirectional sync over the messages)
3. what SHOULD and MUST they do, step by step, to achieve this:
- they identify the _ranges_ that they want to sync over (and define what is meant by that)
- they create the fingerprint
- they encode in some way

etc. 

I think this can be done in a very short paragraph, but will help first-time readers understand the big picture.

2024-12-11 14:20 UTC, jm-clius commented on standards/core/sync.md
> +Chronologically according to the timestamp and
The message IDs are ordered chronologically,....

(Sentence needs a subject and verb)

2024-12-11 14:20 UTC, jm-clius commented on standards/core/sync.md
> +Every range MUST have one of the following types; skip, fingerprint or item set.
Nitpick, but could to typographically highlight repeated concepts

```suggestion
Every range MUST have one of the following types; `skip`, `fingerprint` or `item set`.
```

2024-12-11 14:20 UTC, jm-clius commented on standards/core/sync.md
> +For efficient transmission of timestamps, hashes and ranges. Payloads are delta encoded as follow.
```suggestion
Payloads MUST be delta encoded as follows.
for efficient transmission of timestamps, hashes and ranges. 
```

Nitpick here.

2024-12-11 14:20 UTC, jm-clius commented on standards/core/sync.md
> +Good strategies can be devised but we chose not to.
I would simply say something like:

```suggestion
More sophisticated strategies may be implemented in future.
```

2024-12-11 16:24 UTC, SionoiS commented on standards/core/sync.md
> +Reconciliation is the process of finding differences in 2 sets of message hashes.
I'll try to clarify. Indeed fingerprints are of hashes only and sync ranges are IDs based.

2024-12-11 16:32 UTC, SionoiS commented
> Thanks for this!
> 
> I left some comments below, many of them nitpicks. I think the main comment is around providing some context and a functional overview before jumping into the detail (at least of the `reconciliation` protocol). It can state the protocol flow and wire protocols in very simple terms:
> 
> 1. what agents are involved (two nodes that store Waku messages)
> 2. what are the preconditions and goal (they want to initiate a bidirectional sync over the messages)
> 3. what SHOULD and MUST they do, step by step, to achieve this:
> 
> * they identify the _ranges_ that they want to sync over (and define what is meant by that)
> * they create the fingerprint
> * they encode in some way
> 
> etc.
> 
> I think this can be done in a very short paragraph, but will help first-time readers understand the big picture.

I agree, it's a bit hard to grasps the gist of how reconciliation work ATM.

2025-01-22 13:20 UTC, jm-clius approved these changes
I think this reads very well. Thanks! I have added some comments below, most of them nitpicks or phrasing suggestions which are up to you to address or not.

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +- **Unequal** _fingerprint ranges_ MUST be splitted into smaller ranges. The new type MAY be either _fingerprint_ or _item set_.
```suggestion
- **Unequal** _fingerprint ranges_ MUST be split into smaller ranges. The new type MAY be either _fingerprint_ or _item set_.
```

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +- **Unequal** _fingerprint ranges_ MUST be splitted into smaller ranges. The new type MAY be either _fingerprint_ or _item set_.
Shall we add some guidance here as to when the new type is another fingerprint and when it is an item set? We don't need numbers, unless it's hardcoded, but we could just specify that when the new range is "small enough" the individual IDs can be encoded into an item set.

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +- **Unresolved** _item set_ ranges MUST be checked for differences and marked resolved.
What is the output of "checked for differences"? Does this peer just locally find and keep a list of missing IDs to be requested via transfer or does it also find the list of missing IDs in remote peer and send that in a subsequent message? I think probably the latter, but good idea to be explicit here: Unresolved item set...checked for differences. The IDs missing locally are ... (kept to be requested via transfer)?; the IDs missing in the remote peer are...(compiled and sent in a resolved set?); the item set is marked resolved (and sent to the remote peer?)

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +- **Resolved** _item set_ ranges MUST be checked for differences and become skip ranges.
Is it possible to receive a resolved set simply because this set has been resolved in the remote peer? In other words, it's not resolved by _this_ peer yet?

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +    - _varint_ bytes of the item set length & bytes of every items &
Question, rather than a suggestion - the `&` makes it seem like these items will be concatenated, but if I understand correctly only one of the three listed are added. Perhaps "or" is a bit clearer after "either"?

```suggestion
    - 32 bytes _fingerprint_ or
    - _varint_ bytes of the item set length & bytes of every items or
```

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +The partitioning count is the number of time a range is splitted.
```suggestion
The partitioning count is the number of time a range is split.
```

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +Higher value reduce round trips at the cost of computing more fingerprints.
```suggestion
A higher value reduces round trips at the cost of computing more fingerprints.
```

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +- **Unequal** _fingerprint ranges_ MUST be splitted into smaller ranges. The new type MAY be either _fingerprint_ or _item set_.
Update: you can even point to the implementation section on "item set threshold". Here you can just mention that if number of items in a range fall below _a_ threshold, it becomes an item set rather than just a fingerprint.

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +The threshold for which item sets are sent instead of fingerprints.
```suggestion
The item set threshold determines when item sets are sent instead of fingerprints.
```

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +Higher value sends more items which means higher chance of duplicates but
```suggestion
A higher value sends more items which means higher chance of duplicates but
```

2025-01-22 13:20 UTC, jm-clius commented on standards/core/sync.md
> +reduce the amount of round trips overall.
```suggestion
reduces the amount of round trips overall.
```

2025-01-22 14:29 UTC, SionoiS commented on standards/core/sync.md
> +Waku Sync consists of 2 libp2p protocols; reconciliation and transfer.
Good advice. Thanks!

2025-01-22 14:31 UTC, SionoiS commented on standards/core/sync.md
> +_Ranges_ are encoded into payloads, exchanged between the peers and when the range _fingerprints_ are different, splitted into smaller ones.
Looks like `splitted` is not a word. The more you know...

2025-01-22 14:38 UTC, SionoiS commented on standards/core/sync.md
> +6. Payloads are repeatedly exchanged and differences between the peers are discovered.
`until` is misleading here. I'll try to find a new formulation.

2025-01-22 14:41 UTC, SionoiS commented on standards/core/sync.md
> +7. The synchronization is done when no ranges are left to process.
Well the process is the same. Diffs may be found but nothing changes. I'll try to rephrase.

2025-01-22 15:00 UTC, SionoiS commented on standards/core/sync.md
> +- **Resolved** _item set_ ranges MUST be checked for differences and become skip ranges.
I'm not sure I understand.

An unequal fingerprint range can be received and produce an unresolved item set range.
An unresolved item set range can be received and produce a resolved item set range.
A resolved item set can be received and produces a skip range.

Those are the possible cases.

2025-01-22 15:07 UTC, SionoiS commented on standards/core/sync.md
> +- **Resolved** _item set_ ranges MUST be checked for differences and become skip ranges.
Input -> process -> output

You don't process your own output.

2025-01-22 15:09 UTC, SionoiS commented on standards/core/sync.md
> +- **Unresolved** _item set_ ranges MUST be checked for differences and marked resolved.
Both actually, all differences are sent to the transfer protocol.

I'll try to make this clearer.

2025-01-22 22:03 UTC, merged